# Dependencies
markdown:         kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Michael Gorsuch's Blog
tagline:          "A Hot Mess"
description:      "links from all over the place. curated by <a href='mailto:michael.gorsuch@gmail.com'>michael gorsuch</a>."
url:              https://michaelgorsuch.com
baseurl:          "/"

author:
  name:           'Micahel Gorsuch'
  url:            https://twitter.com/michaelgorsuch

paginate:         5

# Custom vars
github:
  account:           https://github.com/gorsuch

twitter:
  account:           https://twitter.com/michaelgorsuch

plugins: [jekyll-paginate]
