# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            don't panic
tagline:          'dev, ops and dharma'
description:      "dev, ops and dharma. written by <a href='mailto:michael.gorsuch@gmail.com'>michael gorsuch</a>."
url:              http://gorsuch.github.io
baseurl:          /

author:
  name:           'Micahel Gorsuch'
  url:            https://twitter.com/michaelgorsuch

paginate:         5

# Custom vars
github:
  account:           https://github.com/gorsuch

twitter:
  account:           https://twitter.com/michaelgorsuch
